### ISSUE TITLE
Spring Aspects 4.3.x framework Aync error [SPR-15671]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#20230]
**[Abhik Setia](https://jira.spring.io/secure/ViewProfile.jspa?name=abhiksetia)** opened **[SPR-15671](https://jira.spring.io/browse/SPR-15671?redirect=false)** and commented

ava.lang.NoSuchMethodError: org.springframework.scheduling.aspectj.AbstractAsyncExecutionAspect.ajc$around$org_springframework_scheduling_aspectj_AbstractAsyncExecutionAspect$1$6c004c3e(Lorg/aspectj/runtime/internal/AroundClosure;Lorg/aspectj/lang/JoinPoint$StaticPart;Lorg/aspectj/lang/JoinPoint;)Ljava/lang/Object;

I was running version 4.0.x and it was running fine ,after updating it to 4.3.x it caused this error.

---

**Affects:** 4.3.9

**Comment by snicoll** [comment]
I think this issue has run its course now. I hope you found out what the problem.
