### ISSUE TITLE
NoClassDefFoundError: org/jspecify/annotations/Nullable when jspecify is missing at runtime

### ISSUE THREAD

**Issue by javarak** [spring-projects/spring-framework#36447]
**Description**

While migrating from Spring Framework 6.2.10 to 7.0.5, we encounter the following runtime exception during application startup.

**Environment**

- Spring Framework: 7.0.5
- Previous version: 6.2.10
- Java: 17
- Application server: Apache Tomcat
- Spring Security configuration enabled

**Error**

Caused by: org.springframework.beans.factory.BeanCreationException:
Error creating bean with name
'org.springframework.security.config.annotation.web.configuration.HttpSecurityConfiguration':
Injection of autowired dependencies failed

Caused by: java.lang.NoClassDefFoundError: org/jspecify/annotations/Nullable
	at org.springframework.core.Nullness.jSpecifyNullness(Nullness.java:154)
	at org.springframework.core.Nullness.forParameter(Nullness.java:109)
	at org.springframework.core.Nullness.forMethodParameter(Nullness.java:120)
	at org.springframework.core.MethodParameter.isOptional(MethodParameter.java:405)

Caused by: java.lang.ClassNotFoundException: org.jspecify.annotations.Nullable
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(...)

**Observation**

The error indicates that the class org.jspecify.annotations.Nullable is missing at runtime.

**Question**

Is the JSpecify dependency required explicitly when using Spring Framework 7.0.5, or is there another recommended way to resolve this issue without adding the jspecify dependency manually?

**Additional Context**

The application works correctly with Spring Framework 6.2.10, and the issue only appears after upgrading to 7.0.5.

**Comment by bclozel** [comment]
Hello @javarak 

I think the dependency management of your application is probably at fault here. Are you explicitly excluding the jspecify dependency? [spring-core has a compile time dependency on the jspecify annotation jar](https://central.sonatype.com/artifact/org.springframework/spring-core/7.0.5), so we expect this to be available at runtime.

I'm closing this issue for now, don't hesitate to update us with your findings. Thanks!

**Comment by javarak** [comment]
I believe, only for null check we have added this jar(jspecify) and we can not avoid it?

**Comment by bclozel** [comment]
If "spring-core" requires it as a mandatory compile dependency, this means this is a strict requirement. We do compile against optional dependencies in Spring Framework but they don't appear as dependencies in our published POMs.

This is a conscious choice; previously nullness annotations were included in spring-core directly and tradeoffs are in favor of making those a mandatory dependency. As you have found out, excluding that dependency will lead to runtime errors and those are expected because your setup is invalid in the first place.
