### ISSUE TITLE
`@Bean` method matches on returned instance type instead of method return type

### ISSUE THREAD

**Issue by MrThreepwood** [spring-projects/spring-framework#35710]
When upgrading from Spring 3.5.4 to 3.5.5, I'm receiving the error `expected single matching bean but found 2` when attempting to provide a unique bean definition for `IStreamConsumerFactory`.

These beans signature specify that they provide a `IStreamConsumerFactory`, and an `IHistoricalStreamConsumerFactory`.

The `IHistoricalStreamConsumerFactory` does NOT implement `IStreamConsumerFactory`, but the actual implementations of the `IHistroicalStreamConsumerFactory` do. Prior to 3.5.5 this wasn't an issue.

I have not created a simple example, but I assume that

```kotlin
interface A

interface B

class AImpl: A

class BImpl: A, B

@Bean
fun aFactory(): A {
  return AImple()
}

@Bean
fun bFactory(): B {
  return BImple()
}
```

Would be a bare minimum recreation of the issue that would cause a failure as soon as something requested an `A`

**Comment by philwebb** [comment]
This is more likely to be a Spring Framework issue than a Spring Boot issue. We can investigate, but please provide a complete sample application that we can unzip and run. Please also upgrade to the latest 3.5 release in the same and ensure it fails with that version but works with 3.5.4.

**Comment by MrThreepwood** [comment]
[demo 2.zip](https://github.com/user-attachments/files/23216138/demo.2.zip)

Looks like spring has always used the type of the returned class rather than the signature function, and I've run into a weird edge case that may have been unintentionally working before.

I've attached a zip file that works with 3.5.4, but not with 3.5.5 (or 3.5.6 or 3.5.7). The thing that appears to have worked and is now failing is that the B factory takes an A, and then for some reason it worked? It may have been working due to some sort of order of finding/creating beans? It no longer works however.

Is there a way to achieve what I'm actually attempting to do though, which is to provide a Bean using spring that is only matched on the one specific type specified on the bean factory rather than all types implemented/inherited on the returned bean?

**Comment by jhoeller** [comment]
I'm afraid it is exactly as you analyzed: Spring always takes the most specific type available for any particular bean, and this might be dependent on the initialization order indeed. There is no proper way to reduce visibility to just the declared return type: Effectively, that return type is just an early hint before the full instance type becomes available - it was never meant to restrict type exposure.

For a different approach, you could try to declare your `aFactory` method as `@Primary` so that it gets selected over `bFactory` even if the latter's result happens to match as well. Does that work for your purposes?

**Comment by MrThreepwood** [comment]
I'd rather not specify a primary, as that makes it harder to override for tests and the like, but I have other work around options. I can just make B not implement A in my case, and make a function to convert a B into an A. It's not technically backward compatible, but no one should have been referencing the concrete versions anyway.

**Comment by jhoeller** [comment]
Alright, I hope that will work for you. It will definitely be cleaner to not even implement a type that is not meant to be exposed for matching.

For anyone in a similar situation, specific qualifiers for each type are yet another possible solution, or the aforementioned primary marker.
