### ISSUE TITLE
Unable to migrate springframework from 6.2.11 to 7.0.1 with spring-data-jpa 4.0.0

### ISSUE THREAD

**Issue by amateurproof** [spring-projects/spring-framework#35867]
Good morning,
Please, I have my application which is working fine with springframework 6.2.11 and spring-data-jpa 3.5.4, but when I want to migrate it to springframework 7.0.1 and spring-data-jpa 4.0.0, I have error below. which seems to indicate incopartibility between springframework 7 and spring-data-jpa 4. So, I want to know if there is something that I can do to fix it?

```
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [spring/application.xml]
		at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:426)
		at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:347)
		at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:319)
		at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:184)
		at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:220)
		at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.importBeanDefinitionResource(DefaultBeanDefinitionDocumentReader.java:234)
		... 63 more
	Caused by: java.lang.NoSuchMethodError: 'void org.springframework.beans.factory.config.RuntimeBeanReference.<init>(java.lang.String, java.lang.Class)'
		at org.springframework.data.jpa.repository.config.JpaRepositoryConfigExtension.postProcess(JpaRepositoryConfigExtension.java:147)
		at org.springframework.data.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn(RepositoryConfigurationDelegate.java:182)
		at org.springframework.data.repository.config.RepositoryBeanDefinitionParser.parse(RepositoryBeanDefinitionParser.java:77)
		at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:74)
		at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1391)
		at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1371)
		at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:179)
		at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:150)
		at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:96)
		at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:520)
		at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:400)
		... 68 more

```

**Comment by bclozel** [comment]
Hello

This method is not missing and should be present in the RuntimeBeanReference for Spring Framework 7.0.

This points to a dependency management issue in your project. The spring-beans dependency is probably at the wrong version.

You can try and apply the spring framework BOM to consistently get a good set of dependencies.

```xml
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-framework-bom</artifactId>
			<version>7.0.0</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
```

Please check your resolved dependencies and let us know how it goes.

**Comment by amateurproof** [comment]
Hi @bclozel ,
Thanks for your answer. After using dependencyManagement, I noticed that there was a conflict with another library. Once I removed it and added the dependency below, I succeeded in running my application.

`<dependency>
    <groupId>org.eclipse</groupId>
    <artifactId>yasson</artifactId>
    <version>3.0.4</version>
    <scope>compile</scope>
</dependency>`

**Comment by bclozel** [comment]
Thanks for letting us know
