### ISSUE TITLE
NoSuchMethodError for computeIfAbsent after we move to 7.0.0 version

### ISSUE THREAD

**Issue by rakeshreddygundala-ai** [spring-projects/spring-framework#35834]
After we upgrade to 7.0.0 version for org.springframework.spring-test , we are getting NoSuchMethodError for computeIfAbsent 

Our unit tests are failing at moment after we upgrade this to latest version.

java.lang.NoSuchMethodError: 'java.lang.Object org.junit.jupiter.api.extension.ExtensionContext$Store.computeIfAbsent(java.lang.Object, java.util.function.Function, java.lang.Class)'
        at org.springframework.test.context.junit.jupiter.SpringExtension.getTestContextManager(SpringExtension.java:412)
        at org.springframework.test.context.junit.jupiter.SpringExtension.beforeAll(SpringExtension.java:170)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        Suppressed: java.lang.NoSuchMethodError: 'java.lang.Object org.junit.jupiter.api.extension.ExtensionContext$Store.computeIfAbsent(java.lang.Object, java.util.function.Function, java.lang.Class)'
                at org.springframework.test.context.junit.jupiter.SpringExtension.getTestContextManager(SpringExtension.java:412)
                at org.springframework.test.context.junit.jupiter.SpringExtension.afterAll(SpringExtension.java:181)
                ... 1 more

Please help on fix it and provide a solution for this problem.

Thank You.

**Comment by bclozel** [comment]
This missing method [has been introduced in JUnit 6.0](https://docs.junit.org/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/ExtensionContext.Store.html#computeIfAbsent(java.lang.Class)). Are you using JUnit 6.0 as [required by the new baseline](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-7.0-Release-Notes#baseline-upgrades)?

**Comment by Gugu7264** [comment]
> This missing method [has been introduced in JUnit 6.0](https://docs.junit.org/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/ExtensionContext.Store.html#computeIfAbsent(java.lang.Class)). Are you using JUnit 6.0 as [required by the new baseline](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-7.0-Release-Notes#baseline-upgrades)?

I'm curious, why isn't the wiki page linked in the release? Release doesn't mention any breaking change or anything and everything is hidden in that wiki page :/

**Comment by bclozel** [comment]
> I'm curious, why isn't the wiki page linked in the release? Release doesn't mention any breaking change or anything and everything is hidden in that wiki page :/

I have just added a link to the release notes [in the GitHub release](https://github.com/spring-projects/spring-framework/releases/tag/v7.0.0). Hopefully this will help. The 7.0 release on GitHub only highlights changes that were committed after the previous candidate release.

I wouldn't say we are "hiding" content in a wiki page, given that we've been consistently linking to that page in all blog posts announcing all the 7.0 milestone releases this year ([RC1](https://spring.io/blog/2025/10/16/spring-framework-7-0-0-RC1-available-now), [M9](https://spring.io/blog/2025/09/11/spring-framework-7-0-0-M9-available-now), etc), including [the main announcement blog](https://spring.io/blog/2025/11/13/spring-framework-7-0-general-availability). We do maintain that information on a wiki page because we are consistently updating it after the release (even months after, when the community reports feedback about their upgrade experience) - and also because that's what the community [has been using for years](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Older-Release-Notes).

**Comment by Incanus3** [comment]
I've just hit this issue, but it seems the problem goes deeper: `org.springframework.boot:spring-boot-starter-test:4.0.0` brings in `org.mockito:mockito-junit-jupiter:5.20.0`, which depends on `org.junit.jupiter:junit-jupiter-api:5.13.4`. And all the other modular starters (e.g. `spring-boot-starter-jackson-test`) depend on that, so I don't really see, how we (the users) can fix the issue, since on one hand, the new `SpringExtension` (provided by `spring-boot-starter-test`) depends on JUnit 6.0, but on the other, it indirectly forces JUnit 5.13.

**Comment by bclozel** [comment]
@Incanus3 can you create a new Spring Boot issue for this? Ideally, please share a minimal sample application that demonstrates the dependency management problem.

**Comment by Incanus3** [comment]
ok, will try

**Comment by Incanus3** [comment]
ok, this is interesting. I don't exactly understand how this works (I'm no gradle expert, even though I've been developing a reasonably big kotlin app for the last 6 years), but I just created a new spring boot app using spring initializr and when I run `gradlew dependencies` there, I get
```
+--- org.springframework.boot:spring-boot-starter-test -> 4.0.0
|    +--- org.springframework.boot:spring-boot-starter:4.0.0 (*)
|    +--- org.springframework.boot:spring-boot-test:4.0.0
|    |    +--- org.springframework.boot:spring-boot:4.0.0 (*)
|    |    \--- org.springframework:spring-test:7.0.1
|    |         \--- org.springframework:spring-core:7.0.1 (*)
|    +--- org.springframework.boot:spring-boot-test-autoconfigure:4.0.0
|    |    \--- org.springframework.boot:spring-boot-test:4.0.0 (*)
...
|    +--- org.junit.jupiter:junit-jupiter:6.0.1 <-----------
|    |    +--- org.junit.jupiter:junit-jupiter-engine:6.0.1
|    |    |    +--- org.junit:junit-bom:6.0.1
|    |    |    |    +--- org.junit.jupiter:junit-jupiter:6.0.1 (c)
|    |    |    |    +--- org.junit.jupiter:junit-jupiter-api:6.0.1 (c)
|    |    |    |    +--- org.junit.jupiter:junit-jupiter-engine:6.0.1 (c)
|    |    |    |    +--- org.junit.jupiter:junit-jupiter-params:6.0.1 (c)
|    |    |    |    +--- org.junit.platform:junit-platform-engine:6.0.1 (c)
|    |    |    |    +--- org.junit.platform:junit-platform-launcher:6.0.1 (c)
|    |    |    |    \--- org.junit.platform:junit-platform-commons:6.0.1 (c)
|    |    |    +--- org.junit.platform:junit-platform-engine:6.0.1
|    |    |    |    +--- org.junit:junit-bom:6.0.1 (*)
|    |    |    |    +--- org.opentest4j:opentest4j:1.3.0
|    |    |    |    \--- org.junit.platform:junit-platform-commons:6.0.1
|    |    |    |         \--- org.junit:junit-bom:6.0.1 (*)
|    |    |    \--- org.junit.jupiter:junit-jupiter-api:6.0.1
|    |    |         +--- org.junit:junit-bom:6.0.1 (*)
|    |    |         +--- org.opentest4j:opentest4j:1.3.0
|    |    |         \--- org.junit.platform:junit-platform-commons:6.0.1 (*)
|    |    +--- org.junit:junit-bom:6.0.1 (*)
|    |    +--- org.junit.jupiter:junit-jupiter-api:6.0.1 (*)
|    |    \--- org.junit.jupiter:junit-jupiter-params:6.0.1
|    |         +--- org.junit:junit-bom:6.0.1 (*)
|    |         \--- org.junit.jupiter:junit-jupiter-api:6.0.1 (*)
|    +--- org.mockito:mockito-core:5.20.0
|    |    +--- net.bytebuddy:byte-buddy:1.17.7 -> 1.17.8
|    |    +--- net.bytebuddy:byte-buddy-agent:1.17.7 -> 1.17.8
|    |    \--- org.objenesis:objenesis:3.3
|    +--- org.mockito:mockito-junit-jupiter:5.20.0
|    |    +--- org.mockito:mockito-core:5.20.0 (*)
|    |    \--- org.junit.jupiter:junit-jupiter-api:5.13.4 -> 6.0.1 (*) <-------------
```

but when I do this in our app (which doesn't anything special with the dependencies and I've made sure I commented out all mockito dependencies in our build.gradle.kts files), I get
```
|    |    \--- org.springframework.boot:spring-boot-starter-test:4.0.0
|    |         +--- org.springframework.boot:spring-boot-starter:4.0.0 (*)
|    |         +--- org.springframework.boot:spring-boot-test:4.0.0 (*)
|    |         +--- org.springframework.boot:spring-boot-test-autoconfigure:4.0.0
|    |         |    \--- org.springframework.boot:spring-boot-test:4.0.0 (*)
...
|    |         +--- org.junit.jupiter:junit-jupiter:6.0.1 -> 5.14.1 (*) <-----------
|    |         +--- org.mockito:mockito-core:5.20.0
|    |         |    +--- net.bytebuddy:byte-buddy:1.17.7 -> 1.18.2
|    |         |    +--- net.bytebuddy:byte-buddy-agent:1.17.7 -> 1.18.2
|    |         |    \--- org.objenesis:objenesis:3.3
|    |         +--- org.mockito:mockito-junit-jupiter:5.20.0
|    |         |    +--- org.mockito:mockito-core:5.20.0 (*)
|    |         |    \--- org.junit.jupiter:junit-jupiter-api:5.13.4 -> 5.14.1 (*) <-----------
```

**Comment by bclozel** [comment]
This means your dependency management in enforcing that version in your application.
You can track down the problem with Gradle:

```
/gradlew dependencyInsight --dependency org.junit.jupiter:junit-jupiter-api --configuration runtimeClasspath
```

**Comment by Incanus3** [comment]
wow, that's a really useful command, didn't know about that. here is my output for `org.junit:junit-bom` (which is pulling in `junit-jupiter-api`)

```
org.junit:junit-bom:5.14.1
+--- org.junit.jupiter:junit-jupiter:5.14.1
|    +--- project :ea:db (requested org.junit.jupiter:junit-jupiter)
|    |    \--- project :ea:db (*)
|    +--- project :core:db (requested org.junit.jupiter:junit-jupiter)
|    |    +--- project :ea:db (*)
|    |    \--- project :core:db (*)
|    +--- project :core:utils (requested org.junit.jupiter:junit-jupiter)
|    |    +--- project :ea:db (*)
|    |    +--- project :core:db (*)
|    |    +--- project :ea:core
|    |    |    \--- project :ea:db (*)
|    |    +--- project :core:spring-support
|    |    |    +--- project :ea:db (*)
|    |    |    +--- project :core:db (*)
|    |    |    \--- project :core:spring-support (*)
|    |    +--- project :core:models
|    |    |    +--- project :ea:db (*)
|    |    |    +--- project :core:db (*)
|    |    |    +--- project :ea:core (*)
|    |    |    \--- project :core:spring-support (*)
|    |    \--- project :core:utils (*)
|    +--- org.springframework.boot:spring-boot-starter-test:4.0.0 (requested org.junit.jupiter:junit-jupiter:6.0.1)
|    |    +--- org.springframework.boot:spring-boot-starter-webmvc-test:4.0.0
|    |    |    \--- project :ea:db (requested org.springframework.boot:spring-boot-starter-webmvc-test) (*)
|    |    \--- org.springframework.boot:spring-boot-starter-jackson-test:4.0.0
|    |         \--- org.springframework.boot:spring-boot-starter-webmvc-test:4.0.0 (*)
|    \--- org.junit:junit-bom:5.14.1 (*)
+--- org.junit.jupiter:junit-jupiter-api:5.14.1
|    +--- project :core:spring-support (requested org.junit.jupiter:junit-jupiter-api) (*)
|    +--- org.junit.jupiter:junit-jupiter-params:5.14.1
|    |    +--- org.junit:junit-bom:5.14.1 (*)
|    |    \--- org.junit.jupiter:junit-jupiter:5.14.1 (*)
|    +--- org.junit.jupiter:junit-jupiter-engine:5.14.1
|    |    +--- org.junit:junit-bom:5.14.1 (*)
|    |    \--- org.junit.jupiter:junit-jupiter:5.14.1 (*)
|    +--- org.mockito:mockito-junit-jupiter:5.20.0 (requested org.junit.jupiter:junit-jupiter-api:5.13.4) <----------
|    |    \--- org.springframework.boot:spring-boot-starter-test:4.0.0 (*)
|    +--- org.junit:junit-bom:5.14.1 (*)
|    \--- org.junit.jupiter:junit-jupiter:5.14.1 (*)
+--- org.junit.jupiter:junit-jupiter-engine:5.14.1 (*)
+--- org.junit.jupiter:junit-jupiter-params:5.14.1 (*)
+--- org.junit.platform:junit-platform-commons:1.14.1
|    +--- org.junit.jupiter:junit-jupiter-api:5.14.1 (*)
|    +--- org.junit.platform:junit-platform-engine:1.14.1
|    |    +--- org.junit.jupiter:junit-jupiter-engine:5.14.1 (*)
|    |    +--- org.junit.platform:junit-platform-launcher:1.14.1
|    |    |    +--- org.springframework.boot:spring-boot-starter-test:4.0.0 (requested org.junit.platform:junit-platform-launcher) (*)
|    |    |    \--- org.junit:junit-bom:5.14.1 (*)
|    |    \--- org.junit:junit-bom:5.14.1 (*)
|    \--- org.junit:junit-bom:5.14.1 (*)
+--- org.junit.platform:junit-platform-engine:1.14.1 (*)
\--- org.junit.platform:junit-platform-launcher:1.14.1 (*)
```

**Comment by Incanus3** [comment]
I've created a "minimal" repo [here](https://github.com/Incanus3/qwazar-debug-deps). I removed all the code and higher-level modules, but kept the basic ones with their gradle configuration.

**Comment by bclozel** [comment]
Sorry @Incanus3 but I can't spend time debugging dependency management in your application. If you cannot reproduce this with a minimal Spring Boot application, this likely points to a build configuration issue in your application. Maybe consider asking this question on StackOverflow to get help from the Gradle community?

**Comment by Incanus3** [comment]
@bclozel this makes sense of course. I'm working to minimize this repository as much as possible so in the end, it should not be that much different from the one generated by spring initializr. would you be willing to have a final look at it then? the thing is, we really aren't doing anything special with the dependencies here - we aren't overriding the versions of libraries brought in by the the `org.springframework.boot` package anywhere, so it really seems to me, that it's just a matter of some ordering, where in one case the version requested by
```
|    +--- org.mockito:mockito-junit-jupiter:5.20.0 (requested org.junit.jupiter:junit-jupiter-api:5.13.4) <----------
|    |    \--- org.springframework.boot:spring-boot-starter-test:4.0.0 (*)
```
takes precedence and in the other, the version requested by
```
|    +--- org.springframework.boot:spring-boot-starter-test:4.0.0 (requested org.junit.jupiter:junit-jupiter:6.0.1)
```
does. both of these are coming from `spring-boot-starter-test:4.0.0` though.

**Comment by Incanus3** [comment]
OK, I just found the culprit. I'm so sorry @bclozel for wasting your time. the problem comes from the
```kt
dependencyManagement {
    imports {
        mavenBom("org.apache.commons:commons-parent:93")
    }
}
```
which uses
```
 <commons.junit.version>5.14.1</commons.junit.version>
<dependency>
  <groupId>org.junit</groupId>
  <artifactId>junit-bom</artifactId>
  <version>${commons.junit.version}</version>
  <type>pom</type>
  <scope>import</scope>
</dependency>
```

what I don't understand though is that this never appears in any of the `gradle dependencies` and `dependencyInsight` outputs. Anyway, thank you so much for pointing me in the right direction (minimizing the configuration), wouldn't have found it without it.

**Comment by tzorpatrick** [comment]
Hello,
I got the same issue with my migration to Spring boot 4.1.0.

What I did is that I follow the[ previous recommendation](https://stackoverflow.com/a/79917793/14679006). I remove all dependencies related to junit from my setup.

In addtion runnging mvn dependency:tree make me see that there was a dependency dragging junit 4.

That dependency was JUnitParams that I replaced with junit-jupiter-params.

Make sure you do remove all depencies to junit directly. by running mvn dependency:tree exclude all transitive dependency to junit that does come from junit package using <exclusions> directive in maven.

You just need this dependency for junit:
`<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${spring-boot-version}</version>
            <scope>test</scope>
        </dependency>`

Regards,

Ngansop Patrick Tzorneu.
